services:
  - type: web
    name: wave-scanner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --timeout-keep-alive 75
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_WORKERS
        value: 1
      - key: WORKER_TIMEOUT
        value: 300
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1