services:
  - type: web
    name: wave-scanner
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_WORKERS
        value: 4
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    domains:
      - wave-scanner-api